services:
  - type: web
    name: feeltrack-api
    env: docker
    region: oregon
    plan: free   # Usa "starter" si ya pagaste
    branch: main
    autoDeploy: true
    dockerfilePath: Dockerfile
    envVars:
      - key: HF_TOKEN
        value: ${HF_TOKEN}
